language: android

android:
  components:
  - tools
  - tools
  - build-tools-24.0.3
  - android-24
  - extra-android-m2repository
  - extra-android-support

jdk:
- oraclejdk8

before_install:
- 'openssl aes-256-cbc -K $encrypted_b37d956b1dfb_key -iv $encrypted_b37d956b1dfb_iv -in release.keystore.enc -out release.keystore -d || true'

before_script:
- wget http://services.gradle.org/distributions/gradle-2.14.1-bin.zip
- unzip gradle-2.14.1-bin.zip
- export GRADLE_HOME=$PWD/gradle-2.14.1
- export PATH=$GRADLE_HOME/bin:$PATH

script: gradle build

before_deploy:
  - cd app/build/outputs/apk; ls -la; md5sum app-release.apk > md5sum.txt; sha1sum app-release.apk > sha1sum.txt; cd -

deploy:
  provider: releases
  api_key:
    secure: SvdI+5/Gv0eQ93rZ/CRPpnJgPl6Ix56TpjjK7H7VLEqte8jx6H09CCAw0zgJ0rhjCLVp4ijcbI/CeTQ+MpB25dD4msrjGZwkSqVHGNWogAitgoB44+BhCAlSgio+h7ZOTxZ77L27j8yfd9kboSDPhzbPi8mwg6mbMfMfHzcTvR/9Lrv5C6dSXnN/zjOC/+/eex9WTeR8sHIwgnCq42Yo1oIgaJF+HkC1Lc09zxjuvceEMTusO++WVf9CEx9AXcArX2fjF2vLU8dTjkhVA1n4pI90WY+SBiE7JH6nQaR2DazEuJ32YZDsbCjqSVbW+2gl+9OE7ZUOpDez9yOJvHx8tYJw58w1z6zSadLae4UuBTdBXAWA3MwABfda1SL5Z7+AT3yNSO1gARn70rEjPuwgfc7uTQU/diKOv7XUOAryzJTdD6LAHtq9kKj0+ystqk/42AQLTy0eY6NQFjc1T9z+2/C/GenlANkJtOB5DSIue9mp2pXyetRvuM5bwYdmdWzUtHW69tCDOr3DCH7aJpnfwZoYyxisxQMapfeOkYrkmgBK9CH3Vr4NsidbjLLDdFrNJ8v+BcFPKy62MoWXE5MJurn827o6vbLDt2DKiSRWXC++zYHvv3pF962q4Bm2C9LF0ZJHJq1KADvpVduU5GgNE353QWtFGDHblCsolVo3yes=
  file:
    - app/build/outputs/apk/app-release.apk
    - app/build/outputs/apk/md5sum.txt
    - app/build/outputs/apk/sha1sum.txt
  skip_cleanup: true
  on:
   repo: Obsidian-StudiosInc/solitaire
   tags: true
