language: android
android:
  components:
  - tools
  - tools
  - build-tools-24.0.3
  - android-24
  - extra-android-m2repository
  - extra-android-support
jdk:
- oraclejdk8
before_script:
- wget http://services.gradle.org/distributions/gradle-2.14.1-bin.zip
- unzip gradle-2.14.1-bin.zip
- export GRADLE_HOME=$PWD/gradle-2.14.1
- export PATH=$GRADLE_HOME/bin:$PATH
script: gradle build
deploy:
  provider: releases
  api-key:
    secure: PdvPZl8LHoIKYZAcfUKPhEGjZjDhXY6VHS+/Mze0P+DVbgut8XVqNUs0I7SfyM1TZfT7bhBcBxT8hBqijkvjVUis3Mvz4mqlGoEc0Z2s3CrMnvlYtqPvsKlO2qvdxymGV57SE/8opeOkueYN6qB8JGNrZ37IVBoHBEdf6jbZFO1VcWb4Y/pP3qmzQQS9Ivw7HydczdDd0niIQQaG3goGuvFFtxlmk55gDe1JtNcZDS7eirUmhd1dPArLVIv+BOR8QNHLitrEH4OeqfAbFfcAlrYvt33jr8Hp8jXHrWXEapWiKcGPkLcfPk+jPXL4jSn3xUpC/Fomw/bqmNileMrGT/agidYGJbwhPGwvsycrVSppxNpWMe/Jd6i1b9+7RAs4I5pW2OzyWtb5JBLOjHn9RU6i4pO9FqM0mcQKylHcAPswBsJMirFC5prKkLC11pHpiGfDbv9F+B+OdtdZOPioohRNiefiEIRWaLi7OEvFAs0DJjveSdW9YOCJn+uzTI4k7/wAPFb9htcm3Qd68/eNyuckV8oshQE+Lvm9KbF0AfuJX+8yeledJAFP1KNn0P4tHOs4LwDp9k1a2kvSKfPm3WEJ1DZmHmOlovw1ECpNxnWFcobkQ6fvOVVEm5uftfOEPCtfR6+DfO/L7Km+wm1t24EUDzAjEiOn+vgP6qYVeqM=
  file: app/build/outputs/apk/app-debug.apk
  skip_cleanup: true
  on:
    tags: true
