language: android
android:
  components:
  - build-tools-23.0.1
  - android-23
  - extra-android-m2repository
  - extra-android-support
jdk:
  - oraclejdk8
before_script:
  - wget http://services.gradle.org/distributions/gradle-2.14.1-bin.zip
  - unzip gradle-2.14.1-bin.zip
  - export GRADLE_HOME=$PWD/gradle-2.14.1
  - export PATH=$GRADLE_HOME/bin:$PATH
script: "gradle build"
