language: android

android:
  components:
    - tools
    - tools
    - build-tools-24.0.3
    - android-24
    - extra-android-m2repository
    - extra-android-support

jdk:
  - oraclejdk8

env:
  global:
  - secure: Wn4tsp7DbFlJMgn83HEvnFUg3tjDU3NYmWfqOEtrLjJPHMStAj14AYHZwb40zCg23xN/P82wSOjiHEzy3vyU6w86DgCELDHxT1QQGuDUl8SiRbBcdhwAkfj+bhtpuBky8yIUZx6kHQPAwdUEKnCCHWmSZMiVhk9kGiyBSdKGQTUJU6+exgUMUO4ovYYxITlC2h0DF1/rd0u+itQPdyq98q4up7OofhshZxVtsDQKn3ZF7gJC45bRnXKEgAXsL5rNmW9q2XUgVgjBSyFBfM72P8S4uN0T8R4z2tcrhsBD+e4gNSx0qwMMw0aKmq8kIoQ9eBuLi4LW7u4u05AxhfcuWWCHJ6fGaNC3Ec/ep/PbOXhAcGk54/TE6FeYHBv/2EdKbRa32rdWoTY/M/qXfOqj7xv07JzkjjPZh5tXxQqaQX5ysUvsGEeBIMKN1fdw84rVY3a5NomEfs4rKDh/3SvcEjunmsj5+CxA4MyYY5Hgd9KAKJZtY9PU2pnxdlr7IUZtp3ZT7vsr0xmSbkHEprJt7Ph//rLaZSnh15e2Tg9C033sRJ2yvDw7GKSCjTRXBMZadaPSTvqwwwtkNB68k4RzGTa9NgUJpaTYwUAUbTC+YWvVOe0CEIGo+tsbAH34/IJoeZ0BdfRMj/BBwZv5d5HxhvCBADMMQgVMqvswMLcE84k=
  - secure: hg27l127+ejpnmiU3t8CC2fAUVVymPzZyyZa04CDzysxAOMErVpagkhx8w8TzqVDhKzYZoxIxFPcz1JNTfzMnz2FOtngfZix/CFQEyS7XOzYsCZH9cz8yMSYJ/lKXAsQFyKPar2RgQOe92pifQ1I5U0z0vYgQjx8/7oYVdt5BW0f0IJr/kjElazG/m6I/9SVtX88aoTtqOdGPcOGXpHXV16Jys0Sd3A7jW/vOWvasOjUpIK20DKOQZ6k1Xq6AEsb5H+0ek398KA6yDlHJR6GHk9dgyVvA78NNpE7zn0FG2eHu/6b1tcMkKRp8lLsylpWz/raZ011sWEN2/zDSQ0DAeLb9eOwhWZ5KlBgxlL6XceiR0B/X+qKxzVnzxV7IxwPXWGA/gAKwIzHy7h2bgDvYoFSc1rehnA3lPRwVQef/+ePj3S+kDhtanJE87b39AuDQdxTkDiVz1dreVBGLU9sBzhDdI4gFoAEEifgoeRp2ugYE6dseZwewOHR3aDTd0elWxuxF0PL8w4ZKvhkztAPIO70s0T9XKZZmTK+84jSIAayPLiDnDq2zMyWCM/PmeuqUTVhKKoQjeDYJLd2TB1t6vvUM2udQClu3pk5hslQABtAAtxshlPlVMas9IMPWYEEMpJICfNxtcFWZoP8oXLidYZLSRvrEfka8zK3m2q1paM=

before_install:
 - openssl aes-256-cbc -K $encrypted_b37d956b1dfb_key -iv $encrypted_b37d956b1dfb_iv -in release.keystore.enc -out release.keystore -d

before_script:
  - wget http://services.gradle.org/distributions/gradle-2.14.1-bin.zip
  - unzip gradle-2.14.1-bin.zip
  - export GRADLE_HOME=$PWD/gradle-2.14.1
  - export PATH=$GRADLE_HOME/bin:$PATH

script: gradle build

before_deploy:
  - cd app/build/outputs/apk
  - md5sum app-release.apk > app-release.md5
  - sha1sum app-release.apk > app-release.sha1
  - cd -

deploy:
  provider: releases
  api_key:
    secure: SvdI+5/Gv0eQ93rZ/CRPpnJgPl6Ix56TpjjK7H7VLEqte8jx6H09CCAw0zgJ0rhjCLVp4ijcbI/CeTQ+MpB25dD4msrjGZwkSqVHGNWogAitgoB44+BhCAlSgio+h7ZOTxZ77L27j8yfd9kboSDPhzbPi8mwg6mbMfMfHzcTvR/9Lrv5C6dSXnN/zjOC/+/eex9WTeR8sHIwgnCq42Yo1oIgaJF+HkC1Lc09zxjuvceEMTusO++WVf9CEx9AXcArX2fjF2vLU8dTjkhVA1n4pI90WY+SBiE7JH6nQaR2DazEuJ32YZDsbCjqSVbW+2gl+9OE7ZUOpDez9yOJvHx8tYJw58w1z6zSadLae4UuBTdBXAWA3MwABfda1SL5Z7+AT3yNSO1gARn70rEjPuwgfc7uTQU/diKOv7XUOAryzJTdD6LAHtq9kKj0+ystqk/42AQLTy0eY6NQFjc1T9z+2/C/GenlANkJtOB5DSIue9mp2pXyetRvuM5bwYdmdWzUtHW69tCDOr3DCH7aJpnfwZoYyxisxQMapfeOkYrkmgBK9CH3Vr4NsidbjLLDdFrNJ8v+BcFPKy62MoWXE5MJurn827o6vbLDt2DKiSRWXC++zYHvv3pF962q4Bm2C9LF0ZJHJq1KADvpVduU5GgNE353QWtFGDHblCsolVo3yes=
  file:
    - app/build/outputs/apk/app-debug.apk
    - app/build/outputs/apk/app-release.apk
    - app/build/outputs/apk/app-release.md5
    - app/build/outputs/apk/app-release.sha1
  skip_cleanup: true
  on:
    repo: Obsidian-StudiosInc/solitaire
    tags: true
